# Generated by Django 5.0.4 on 2024-11-15 15:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupParticipate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MessageGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_ata', models.DateTimeField(auto_now_add=True)),
                ('users', models.ManyToManyField(related_name='user_group', through='chat.GroupParticipate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupparticipate',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.messagegroup'),
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_group_message', to=settings.AUTH_USER_MODEL)),
                ('message_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='all_group_message', to='chat.messagegroup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OneToOneMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('message_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_personal_message', to=settings.AUTH_USER_MODEL)),
                ('message_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='receiver_message', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
