# Generated by Django 5.0.4 on 2024-06-29 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_status',
            field=models.BooleanField(default=True),
        ),
    ]
